DROP TABLE `TBL_ACTION`;

CREATE TABLE  IF NOT EXISTS `TBL_ACTION`
(
    `USER_NO`    INTEGER NOT NULL COMMENT '회원번호',
    `POST_NO`    INTEGER NOT NULL COMMENT '게시물 번호',
    `ACTION_TYPE`    VARCHAR(10) NOT NULL COMMENT '반응구분',
    `COMMENT_NO`    INTEGER COMMENT '댓글 번호'
) COMMENT = '반응';


DROP TABLE `TBL_CHECK`;

CREATE TABLE `TBL_CHECK`
(
    `CHECK_NO`    INTEGER NOT NULL COMMENT '출석번호',
    `USER_NO`    INTEGER NOT NULL COMMENT '회원번호',
    `CHECK_DATE`    DATE NOT NULL COMMENT '날짜',
    `CHECK_STATUS`    BOOLEAN NOT NULL COMMENT '출석여부',
    `CHECK_ALL_NO`    INTEGER COMMENT '누적출석수',
 PRIMARY KEY ( `CHECK_NO` )
) COMMENT = '출석체크';

ALTER TABLE `TBL_CHECK`
 ADD CONSTRAINT `TBL_CHECK_PK` PRIMARY KEY ( `CHECK_NO` );

DROP TABLE `TBL_COMMENT`;

CREATE TABLE `TBL_COMMENT`
(
    `COMMENT_NO`    INTEGER NOT NULL COMMENT '댓글 번호',
    `COMMENT_CONTENT`    VARCHAR(200) NOT NULL COMMENT '댓글 내용',
    `USER_NO`    INTEGER NOT NULL COMMENT '댓글 작성자',
    `COMMNET_REPORT`    INTEGER COMMENT '댓글 신고 수',
    `COMMNET_DATE`    DATE NOT NULL COMMENT '댓글 작성날짜',
    `POST_NO`    INTEGER NOT NULL COMMENT '게시물 번호',
 PRIMARY KEY ( `COMMENT_NO` )
) COMMENT = '댓글';

ALTER TABLE `TBL_COMMENT`
 ADD CONSTRAINT `TBL_COMMENT_PK` PRIMARY KEY ( `COMMENT_NO` );


DROP TABLE `TBL_MBTI`;

CREATE TABLE `TBL_MBTI`
(
    `MBTI_TYPE`    VARCHAR(10) NOT NULL COMMENT 'MBTI 유형',
    `MBTI_NO`    INTEGER NOT NULL COMMENT 'MBTI 번호',
    `MBTI_STATUS`    BOOLEAN NOT NULL COMMENT 'MBTI 테스트 유무',
    `USER_NO`    INTEGER NOT NULL COMMENT '회원번호',
 PRIMARY KEY ( `MBTI_NO` )
) COMMENT = 'MBTI';

ALTER TABLE `TBL_MBTI`
 ADD CONSTRAINT `TBL_MBTI_PK` PRIMARY KEY ( `MBTI_NO` );


DROP TABLE `TBL_MBTI_TEST`;

CREATE TABLE `TBL_MBTI_TEST`
(
    `MBTI_TYPE`    VARCHAR(10) NOT NULL COMMENT 'MBTI 유형',
    `MBTI_IMG`    BLOB NOT NULL COMMENT 'MBTI 이미지',
    `MBTI_QUESTION`    VARCHAR(300) NOT NULL COMMENT 'MBTI 질문',
    `MBTI_RESULT`    VARCHAR(100) NOT NULL COMMENT 'MBTI 결과',
    `MBTI_INFO`    VARCHAR(200) NOT NULL COMMENT 'MBTI 해석',
 PRIMARY KEY ( `MBTI_TYPE` )
) COMMENT = 'MBTI 테스트';

ALTER TABLE `TBL_MBTI_TEST`
 ADD CONSTRAINT `TBL_MBTI_TEST_PK` PRIMARY KEY ( `MBTI_TYPE` );


DROP TABLE `TBL_NOTICE`;

CREATE TABLE `TBL_NOTICE`
(
    `NOTICE_NO`    INTEGER NOT NULL COMMENT '공지사항번호',
    `NOTICE_TITLE`    VARCHAR(20) NOT NULL COMMENT '공지사항제목',
    `NOTICE_CONTENT`    VARCHAR(200) NOT NULL COMMENT '공지사항내용',
    `USER_NO`    INTEGER NOT NULL COMMENT '관리자번호',
    `NOTICE_DATE`    DATE NOT NULL COMMENT '공지사항등록일',
    `NOTICE_CATEGORY`    VARCHAR(30) NOT NULL COMMENT '공지사항카테고리',
 PRIMARY KEY ( `NOTICE_NO` )
) COMMENT = '공지사항';

ALTER TABLE `TBL_NOTICE`
 ADD CONSTRAINT `TBL_NOTICE_PK` PRIMARY KEY ( `NOTICE_NO` );


DROP TABLE `TBL_POST`;

CREATE TABLE `TBL_POST`
(
    `POST_NO`    INTEGER NOT NULL COMMENT '게시물 번호',
    `POST_TITLE`    VARCHAR(20) NOT NULL COMMENT '게시물 제목',
    `POST_CONTENTS`    VARCHAR(2000) NOT NULL COMMENT '게시물 내용',
    `POST_CATEGORY`    VARCHAR(30) NOT NULL COMMENT '게시물 카테고리',
    `POST_WRITER`    INTEGER NOT NULL COMMENT '게시물 작성자',
    `POST_DATE`    DATE NOT NULL COMMENT '게시물 작성날짜',
    `COMMENTS_NUMBER`    INTEGER COMMENT '게시물 댓글수',
    `SCARY_NUMBER`    INTEGER COMMENT '게시물 무서워요 수',
    `POST_REPORT`    INTEGER COMMENT '게시물 신고수',
    `POST_IMAGE`    BLOB COMMENT '게시물 이미지',
    `POST_FAVORITE`    BOOLEAN NOT NULL COMMENT '게시물 즐겨찾기',
 PRIMARY KEY ( `POST_NO` )
) COMMENT = '게시판';

ALTER TABLE `TBL_POST`
 ADD CONSTRAINT `TBL_POST_PK` PRIMARY KEY ( `POST_NO` );


DROP TABLE `TBL_RANK`;

CREATE TABLE `TBL_RANK`
(
    `RANK_NO`    INTEGER NOT NULL COMMENT '등급 번호',
    `RANK`    VARCHAR(30) COMMENT '등급',
    `CHECK_NO`    INTEGER NOT NULL COMMENT '출석번호',
 PRIMARY KEY ( `RANK_NO` )
) COMMENT = '등급';

ALTER TABLE `TBL_RANK`
 ADD CONSTRAINT `TBL_RANK_PK` PRIMARY KEY ( `RANK_NO` );


DROP TABLE `TBL_REPORT`;

CREATE TABLE `TBL_REPORT`
(
    `REPORT_NO`    INTEGER NOT NULL COMMENT '신고 코드',
    `REPROT_REASON`    VARCHAR(30) COMMENT '신고 사유',
    `REPORT_DATE`    DATE COMMENT '신고날짜',
    `USER_NO`    INTEGER NOT NULL COMMENT '신고인',
    `THIS_NUMBER`    INTEGER NOT NULL COMMENT '대상번호',
 PRIMARY KEY ( `REPORT_NO` )
) COMMENT = '신고';

ALTER TABLE `TBL_REPORT`
 ADD CONSTRAINT `TBL_REPORT_PK` PRIMARY KEY ( `REPORT_NO` );


DROP TABLE `TBL_REPORT_TYPE`;

CREATE TABLE `TBL_REPORT_TYPE`
(
    `THIS_NO`    INTEGER NOT NULL COMMENT '대상번호',
    `POST_NO`    INTEGER COMMENT '게시물 번호',
    `COMMENT_NO`    INTEGER COMMENT '댓글 번호',
 PRIMARY KEY ( `THIS_NO` )
) COMMENT = '신고대상';

ALTER TABLE `TBL_REPORT_TYPE`
 ADD CONSTRAINT `TBL_REPORT_TYPE_PK` PRIMARY KEY ( `THIS_NO` );


DROP TABLE `TBL_USER`;

CREATE TABLE `TBL_USER`
(
    `USER_NO`    INTEGER NOT NULL COMMENT '회원번호',
    `USER_TYPE`    VARCHAR(30) NOT NULL COMMENT '회원 구분',
    `USER_ID`    VARCHAR(30) NOT NULL COMMENT '회원 아이디',
    `USER_PWD`    VARCHAR(30) NOT NULL COMMENT '회원 비밀번호',
    `USER_NAME`    VARCHAR(30) NOT NULL COMMENT '회원 닉네임',
    `EMAIL`    VARCHAR(30) COMMENT '회원 이메일',
    `BIRTHDAY`    DATE COMMENT '회원 생년월일',
    `USER_IMAGE`    BLOB COMMENT '회원 프로필사진',
    `PHONE`    VARCHAR(30) NOT NULL COMMENT '휴대폰 번호',
    `RANK_NO`    INTEGER NOT NULL COMMENT '등급 번호',
 PRIMARY KEY ( `USER_NO` )
) COMMENT = '회원';

ALTER TABLE `TBL_USER`
 ADD CONSTRAINT `TBL_USER_PK` PRIMARY KEY ( `USER_NO` );


